### PR TITLE
[WIP] Add script for bundling all lessons into a PDF

### PR DESCRIPTION
**Pull request by bauglir**
This script requires Jupyter's `nbconvert` and `wkhtmltopdf` (available from http://wkhtmltopdf.org/) to be available. In fact it should be passed to `nbconvert` as a configuration file as that's what it is.

The resulting file is quite large (around 35MB which can be compressed with an additional step to about 23MB). I'll put a copy of the 'current' version in our shared Dropbox folder so you can take a look at it.

To be added:
* [x] Start new chapters (i.e. notebooks) on a new page
* [x] Add title page
* [ ] Add a table of contents (check to see if page numbers are a possibility)
* [ ] Add Tjalling's slides

### CODE REVIEW

**Comment by marcocox** [comment]
Thanks Joris. Let's wait for Bert's feedback. For now the main comments I have are:

1. Chapters (notebooks?) should start at a new page to highlight the structure of the document.
2. There should be a table of contents (preferably incl. page numbers, although I have no idea (yet) how difficult that would be).

**Comment by bauglir** [comment]
From what I've seen these should be relatively easy to implement. I actually came up with the exact same points, but decided to hold off for now to see if this is the way we'd want to go :)

As a bit of background, the scripts explicitly renders to HTML first and only then to PDF as going directly to PDF causes issues with the MathJax integration (LaTeX doesn't like the embedded LaTeX in the notebooks and starts complaining about that). Also this way makes it a bit easier to manipulate the document if we want to.

**Comment by bertdv** [comment]
I have only a pon with me so feedback is short. It looks great, thanks Joris. Agreed w Marco´s remarks on TOC and newpage for chapters. Also noticed that in my mobile pdf renderer the latex command \underbrace is nto rendered well, nor are the \rightoverarrows for messages. Anyway thats probably part of wkhtmltopdf and beyond our control. Eventually I woudl also like

3. add a title page    
4. Add tjalling s slides

But that is for later. Thanks.

**Comment by bauglir** [comment]
Hmm I'll take a look at those LaTeX commands. Those should've rendered okay if they render on okay on the slides (MathJax takes care of all the rendering everywhere). It may be that I need to wait a bit longer for MathJax to finish rendering.

For the title page the same thing holds as the ToC. Should be pretty trivial to add (just make an HTML page :)). Same thing basically goes for Tjalling's slides. If they can be exported into (preferably) HTML, it should be fairly easy to add them to the bundle.

**Comment by bertdv** [comment]
Thanks for adding a cover page. BTW, the class ID is 5SSB0 (not SSB0). Can you please update the bundler script to the correct ID?

**Comment by bauglir** [comment]
I haven't applied any styling to the table of contents currently. This can be added, but needs to be done using XSL Stylesheets. I'm not familiar with those and didn't want to get into it just yet. We can revisit this decision if so desired.

**Comment by bauglir** [comment]
I believe I have now added/fixed all requests/bugs that were mentioned. The only ones I wasn't able to find were the `\underbrace` and `\overrightarrows` commands you mentioned were in there @bertdv. Can you take a look at the new PDF I put on Dropbox and see if they're still there (and if so let me know where they are).

The new PDF is _significantly_ smaller, clocking in at a tad over 3.5MB. The rendering quality of the text has gone down a bit, and I think this has to do with the version of `wkhtmltopdf` I had to use to get the page breaks working in combination with the custom font. If it's a real nuisance we can look into alternatives.

I'll be out snowboarding next week, but will be able to make adjustments when I get back.

**Comment by bertdv** [comment]
OK , @bauglir  thanks a lot for the work. There are indeed problems with the math formatting in particular w `\underbrace` (eg pg 107) and `\overrightarrow` (eg pg 112), but there are more math formatting problems, eg top formula at pg 124. 

We' ll deal with it after you get back. Enjoy the snowboarding.

**Comment by bauglir** [comment]
Ah now I see what you mean. I thought you meant that they weren't even rendering. We'll look into this when I get back! First thing to check is whether it actually renders properly in the HTML.

**Comment by bertdv** [comment]
Not sure if this helps but the pdf looks awesome: https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/tree/master/pdf

**Comment by bauglir** [comment]
That one renders through LaTeX first, which causes a whole slew of other problems. I have just come up with another avenue to explore. I'd still prefer to just have the HTML render nicely and print that (although there appear to be some issues with stuff like `underbars`, etc. there).

**Comment by bauglir** [comment]
I'm now rendering the bundle using different software. This means that currently there is no table of contents. This may be something we can add, but it's probably not worth it. As far as I can see all previous render bugs do not exist in this version. I've put a version of the render on Dropbox in `/data`.

The bundling process can now also be run inside a Docker container. The instructions for how to do so have been added to the README.

**Comment by bertdv** [comment]
Wow, this is awesome! Better than I had hoped for. I think this can be merged w master. Great job!

**Comment by bauglir** [comment]
Alright, this should pretty much be the final version of the bundler. One possible issue remains. For some reason the links in the generated PDF point to the original HTML file from which it is generated. This only happens using the tool I'm currently using. So the question is, do we get rid of the table of contents entirely or do we just disable the links? Or do we not really care and 'wait and see' to see if the issue resolves itself automatically when a newer version is released?

**Comment by bertdv** [comment]
As discussed yesterday, let's disable the links for now. I like the TOC, even without the links and page numbers.  FYI the class website has a link to AIP-5SSB0.pdf in the dropbox folder. Please don't change the file name and location anymore (or we need to find a better way to host the file).

**Comment by bertdv** [comment]
As discussed, we close the PR since the bundle is fine now.

**Pull request merged**
